# Generated by Django 6.0.4 on 2026-06-09 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone_portaria', models.CharField(max_length=20)),
                ('total_vagas_visitantes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FaturaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status_pagamento', models.CharField(default='Pendente', max_length=20)),
                ('codigo_barras', models.CharField(max_length=48)),
                ('data_emissao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('senha_hash', models.CharField(max_length=255)),
                ('eh_proprietario', models.BooleanField(default=True)),
                ('is_adimplente', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('taxa_reserva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade_maxima', models.IntegerField()),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('tipo_piso', models.CharField(max_length=50)),
                ('possui_iluminacao_noturna', models.BooleanField(default=False)),
                ('esporte_principal', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('taxa_reserva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade_maxima', models.IntegerField()),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('permite_som_alto', models.BooleanField(default=True)),
                ('quantidade_cadeiras', models.IntegerField()),
                ('tipo_cozinha', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sindico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('senha_hash', models.CharField(max_length=255)),
                ('inicio_mandato', models.DateField()),
                ('fim_mandato', models.DateField()),
                ('status_gestao', models.CharField(default='Ativo', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('data_registro_veiculo', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('total_andares', models.IntegerField()),
                ('total_unidades_por_andar', models.IntegerField()),
                ('condominio_id', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='ComprovantePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autenticacao_bancaria', models.CharField(max_length=100)),
                ('data_pagamento', models.DateField()),
                ('canal_pagamento', models.CharField(max_length=50)),
                ('fatura_id', models.OneToOneField(db_column='fatura_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.faturafinanceira')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('morador_id', models.ForeignKey(db_column='morador_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.morador')),
                ('quadra_id', models.ForeignKey(blank=True, db_column='quadra_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.quadra')),
                ('salao_id', models.ForeignKey(blank=True, db_column='salao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.salao')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Aberta', max_length=20)),
                ('resposta_sindico', models.TextField(blank=True, null=True)),
                ('morador_id', models.ForeignKey(db_column='morador_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.morador')),
                ('quadra_id', models.ForeignKey(blank=True, db_column='quadra_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.quadra')),
                ('salao_id', models.ForeignKey(blank=True, db_column='salao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.salao')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('andar', models.IntegerField()),
                ('tipo', models.CharField(default='Apartamento', max_length=50)),
                ('fracao_ideal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bloco_id', models.ForeignKey(db_column='bloco_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.bloco')),
                ('morador_responsavel_id', models.ForeignKey(blank=True, db_column='morador_responsavel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.morador')),
            ],
        ),
        migrations.AddField(
            model_name='faturafinanceira',
            name='unidade_id',
            field=models.ForeignKey(db_column='unidade_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.unidade'),
        ),
        migrations.CreateModel(
            name='UnidadeAreaComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_liberacao_acesso', models.DateField(auto_now_add=True)),
                ('is_bloqueado_por_inadimplencia', models.BooleanField(default=False)),
                ('quadra_id', models.ForeignKey(blank=True, db_column='quadra_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.quadra')),
                ('salao_id', models.ForeignKey(blank=True, db_column='salao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.salao')),
                ('unidade_id', models.ForeignKey(db_column='unidade_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='MoradorVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculo', models.DateField(auto_now_add=True)),
                ('is_veiculo_principal', models.BooleanField(default=True)),
                ('morador_id', models.ForeignKey(db_column='morador_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.morador')),
                ('veiculo_id', models.ForeignKey(db_column='veiculo_id', on_delete=django.db.models.deletion.CASCADE, to='condominio.veiculo')),
            ],
        ),
    ]
